---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helloenv-staging
  namespace: flux-system
spec:
  interval: 30s
  path: ./demo/kustomize/staging/
  prune: true
  sourceRef:
    kind: GitRepository
    name: helloenv-app
  targetNamespace: helloenv-staging
